project:
  type: website

website:
  title: "Rookdatascientist"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - stars.qmd
      - chess.qmd
      - cv.qmd
  cookie-consent: true

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: source

