project:
  type: website

website:
  title: "Rookdatascientist"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - chess.qmd

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: source

